<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OxVVqoY' shared service.

return $this->privates['.service_locator.OxVVqoY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('userRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\Repository\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}));
