<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Menu\MenuBuilder' shared autowired service.

include_once $this->targetDirs[3].'/src/Menu/MenuBuilder.php';

return $this->privates['App\Menu\MenuBuilder'] = new \App\Menu\MenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['translator'] ?? $this->getTranslatorService()), 'en|ru', 'en');
